# Notebook which is used for visualization of default preprocessing method

In [27]:
import os
import sys

def adding_module_path():
    module_path = os.path.abspath(os.path.sep.join([".."]*3))

    if module_path not in sys.path:
        sys.path.append(module_path)

adding_module_path()

In [28]:
from src.config.run_prep import run_prep
run_prep()

In [29]:
run_prep()

Running preperation of packages


[nltk_data] Downloading package punkt to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [19]:
from src.preprocessing.preprocessor import TextPreprocessor
preprocessor = TextPreprocessor()

Creating shorting method with min = 3
Creating lemma method with instance <WordNetLemmatizer>


In [20]:
method = preprocessor.create_preprocess_string_func([
    preprocessor.to_lowercase,
    preprocessor.strip_punctuation,
    preprocessor.strip_tags,
    preprocessor.strip_multiple_whitespaces,
    preprocessor.strip_numeric,
    preprocessor.strip_stopwords,
    preprocessor.strip_short,
    preprocessor.lemma_text
])

In [21]:
from src.utils.create_path_to_gutenberg import get_path_to_gutenberg_sets
from src.data_loading.get_dataset_object_from import get_dataset_object_from_path, get_datasets
from src.config.config import PATH_TO_DATASET_FOLDER_TEST

In [22]:
path_data, path_authors = get_path_to_gutenberg_sets(10, 3, PATH_TO_DATASET_FOLDER_TEST)

In [23]:
train, valid, test = get_datasets(path_data, ';', preprocessor.default_preprocessing())

In [24]:
for x in train:
    print(x)
    break

(<tf.Tensor: shape=(), dtype=string, numpy=b'miss nugent received information civil bow renewed conversation murchison face showed keen appreciation situation hardy difficulty masking feeling long time coming said mr kybird smiling archly young people keeping company forget everybody trouble adn ardy giving arm ave got'>, <tf.Tensor: shape=(), dtype=int32, numpy=1865>)


In [25]:
train_raw, valid_raw, test_raw = get_datasets(path_data, ';', None)

In [26]:
for x in train_raw:
    print(x)
    break

(<tf.Tensor: shape=(), dtype=string, numpy=b'"""""""Miss Nugent received the information with a civil bow, and renewed her conversation with Dr. Murchison, whose face showed such a keen appreciation of the situation that Hardy had some difficulty in masking his feelings. """"""""They\'re a long time a-coming,"""""""" said Mrs. Kybird, smiling archly """"""""but there, when young people are keeping company they forget everything and everybody. They didn\'t trouble about me if it \'adn\'t been for Mr. \'Ardy giving me \'is arm I should never \'ave got here."""""""""""""""'>, <tf.Tensor: shape=(), dtype=int32, numpy=1865>)
