In [2]:
import os
import sys

def adding_module_path():
    module_path = os.path.abspath(os.path.join('..'))

    if module_path not in sys.path:
        sys.path.append(module_path)

adding_module_path()

In [3]:
from src.data_preparing.build.gutenberg_builder import GutenbergBuilder
from src.app.project_setup import ProjectSetup
from src.data_preparing.split.run_split_deps_on_stats import run_split_deps_on_stats_same_dir
from src.utils.create_path_to_gutenberg import create_path_to_gutenberg_sentence_authors_sentence, create_path_to_gutenberg_authors
from src.utils.create_test_dataset_from import create_test_dataset_from
from src.data_preparing.split.run_split_deps_on_stats import run_split_deps_on_stats_same_dir
from src.utils.create_path_to_gutenberg import create_path_to_gutenberg_sentence_authors_sentence
from src.config.config import PATH_TO_DATASET_FOLDER_TEST, PATH_TO_DATASET_FOLDER_TEST, AUTHORS_FILE_NAME

from src.tokenizers.prepare_dataset_from_tokenizer import prepare_dataset_from_tokenizer
from src.tokenizers.transformer_tokenizer import TransformerTokenizer
import tensorflow as tf
from src.encoder.create_encoder_from_path import create_encoder_from_path
from src.testing.get_testing_dataset import dataset as test_dataset
from src.data_loading.get_dataset_object_from import get_dataset_object_from_path, get_datasets
from src.utils.create_path_to_gutenberg import get_paths_to_gutenberg, get_path_to_gutenberg_sets

In [4]:
PATH_TO_DATASET_FOLDER_TEST

'C:\\Users\\Vojta\\Desktop\\diploma\\data_test'

In [5]:
from transformers import TFAutoModel
from src.experiments.settings import LearningSettings
from transformers import AutoConfig
from src.types.transformer_name import TransformerName
from src.types.processing_type import PreprocessingType
from src.preprocessing.preprocessing_factory import PreprocessingFactory
from src.types.transformer_pooling import TransformerPooling
from src.config.run_prep import run_prep
run_prep()

Running preperation of packages


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Vojta\Desktop\diploma\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Vojta\Desktop\diploma\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Vojta\Desktop\diploma\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [6]:
settings = LearningSettings()

In [7]:
model_name = TransformerName.BertBaseUncased.value

In [233]:
preprocessing_factory = PreprocessingFactory()

Creating shorting method with min = 3
Creating lemma method with instance <WordNetLemmatizer>


In [8]:
config = AutoConfig.from_pretrained(model_name, output_hidden_states=True)

In [9]:
path_data, path_authors = get_path_to_gutenberg_sets(6, 3, PATH_TO_DATASET_FOLDER_TEST)

In [215]:
path_data

('/home/usp/pro0255/diploma/data_test/gutenberg/10Authors/Sentence3/train.csv',
 '/home/usp/pro0255/diploma/data_test/gutenberg/10Authors/Sentence3/valid.csv',
 '/home/usp/pro0255/diploma/data_test/gutenberg/10Authors/Sentence3/test.csv')

In [235]:
train, valid, test = get_datasets(path_data, ';', preprocessing_factory.create(PreprocessingType.Default))

In [55]:
from src.experiments.experiment_run_wrapper import ExperimentRunWrapper
from src.experiments.settings import LearningSettings
from src.tokenizers.transformer_tokenizer import TransformerTokenizer
from src.encoder.create_encoder_from_path import create_encoder_from_path
from transformers import TFAutoModel, AutoConfig
import tensorflow as tf
import os
from src.tokenizers.prepare_dataset_from_tokenizer import prepare_dataset_from_tokenizer
from src.models.transformer.bert_pooling_layer import BertPoolingLayer
import time
from src.experiments.experiment_summarization import ExperimentSummarization
from src.types.experiment_summarization_fields import ExperimentSummarizationFields
from src.config.learning_config import TRANSFORMER_EPOCHS
from src.experiments.descriptions.create_description import (
    create_description_for_transformer_with_dense_head
)
import os
from src.config.config import TEXT_COLUMN, LABEL_COLUMN, VALIDATION_SIZE
from src.experiments.experiment_description import ExperimentDescription
from src.types.transformer_pooling import TransformerPooling
from src.types.prediction_model_type import PredictionModelType
from src.types.net_type import NetType
from src.types.embedding_type import EmbeddingType
from src.types.processing_type import PreprocessingType
import time
from src.data_loading.get_dataset_object_from import get_dataset_all
from src.utils.from_dataset_arrays import from_dataset_dataframe
from src.utils.split_dataframe import split_dataframe
from src.utils.normalize_dataframe_to_size import normalize_dataframe_to_size
from src.utils.create_dataset_from_dataframe import create_dataset_from_Xy
import pandas as pd
from src.utils.generate_random_stamp import generator_random_stamp
from src.types.transformer_pooling import TransformerPooling

In [56]:
from src.data_loading.get_dataset_object_from import get_dataset_all
NUMBER_OF_AUTHORS = 6
NUMBER_OF_SENTENCES = 3

In [57]:
data, paths = get_dataset_all(NUMBER_OF_AUTHORS, NUMBER_OF_SENTENCES)

Creating shorting method with min = 3
Creating lemma method with instance <WordNetLemmatizer>
Loading dataset from=C:\Users\Vojta\Desktop\diploma\data\gutenberg\6Authors\Sentence3\data.csv


In [58]:
all_data = from_dataset_dataframe(data[0])

In [60]:
data_normalized = normalize_dataframe_to_size(all_data, 500)
X_train, X_test, y_train, y_test = split_dataframe(data_normalized)
df = pd.DataFrame()
df[TEXT_COLUMN] = X_train
df[LABEL_COLUMN] = y_train
X_train, X_val, y_train, y_val = split_dataframe(df, VALIDATION_SIZE)

train_ds = create_dataset_from_Xy(X_train, y_train)
test_ds = create_dataset_from_Xy(X_test, y_test)
val_ds = create_dataset_from_Xy(X_val, y_val)

13195    guess guess fun like need afraid end possible ...
16684    coming wanted moved saw overcome ike trim bran...
38535    father asked nefert doubtfully friend listen u...
28576    possibly disloyalty parent sign satanic source...
37822    foundation temple outside port cocquerel immed...
Name: text, dtype: object

In [73]:
for x in val_ds:
    print(x)
    break

(<tf.Tensor: shape=(), dtype=string, numpy=b'guess guess fun like need afraid end possible guessing furnish meaning word sure right word hint form sound spelling throw hint keep secret slightest slight shadow hint lie meagerly suggestive fact spalleggiato carry word egg stomach'>, <tf.Tensor: shape=(), dtype=int32, numpy=53>)


In [62]:
for x in data[0]:
    print(x)
    break

(<tf.Tensor: shape=(), dtype=string, numpy=b'thank goodness come open door s missis screech'>, <tf.Tensor: shape=(), dtype=int32, numpy=1865>)


In [15]:
tokenizer = TransformerTokenizer(
    model_name, 
    create_encoder_from_path(
        paths[1]
    )
)

In [17]:

from enum import Enum

class TransformerPooling(Enum):
    LastHiddenState = "last_hidden_state"
    Pooler = "pooler_output"
    HiddenStates = "hidden_states"

In [63]:
transformer = TFAutoModel.from_config(config)

In [23]:
class BertPoolingLayer(tf.keras.layers.Layer):
    def call(self, inputs, pooling_type):
        if pooling_type == TransformerPooling.LastHiddenState:
            last_hidden_state = inputs[TransformerPooling.LastHiddenState.value]
            return tf.reduce_mean(last_hidden_state, axis=1)
            
            
        if pooling_type == TransformerPooling.Pooler:
            pooler = inputs[TransformerPooling.Pooler.value]
            return pooler
        
        
        # if pooling_type == TransformerPooling.HiddenStates:
        #     #TODO: deal with hidden state
        #     selector = inputs[TransformerPooling.HiddenStates.value]
            
        #     layers = tf.convert_to_tensor(selector)[-1]
            
        #     if tf.shape(tf.shape(layers)) > 3:
        #         #print(layers)
        #         print('A')
        #         layers_together = tf.reduce_mean(layers, axis=0)
        #         average_sentence_words = tf.reduce_mean(layers_together, axis=1)
        #         cls = layers_together[:, 0, :]
        #         return cls
                
                
        #         #print(average_sentence_words)
        #         #layers = tf.reduce_mean(layers, axis=0, keepdims=False)
        #         #cls = layers[:, 0, :]
        #         #average_sentence_words = tf.reduce_mean(layers[:, 1:tf.shape(layers)[1]-1, :], axis=1)
        #         #return average_sentence_words
        #     else:
        #         print('B')
                
        #         #return tf.reduce_mean(layers, axis=1)
        #         cls = layers[:, 0, :]
        #         #return cls
        #         average_sentence_words = tf.reduce_mean(layers[:, 1:tf.shape(layers)[1]-1, :], axis=1)
        #         return average_sentence_words

In [64]:
import tensorflow as tf
from src.types.transformer_pooling import TransformerPooling
from src.types.transformer_pooling_strategy import TransformerPoolingStrategy


def verify_bert_pooling_input(
    pooling_type,
    transformer_pooling_strategy=None,
    transformer_start_index=None,
    transformer_end_index=None,
):
    if pooling_type in [
        TransformerPooling.LastHiddenState,
        TransformerPooling.Pooler,
    ] and (
        transformer_pooling_strategy is not None
        or transformer_start_index != -1
        or transformer_end_index != -1
    ):
        assert Exception(
            f"Cannot use pooling strategy when is not used {TransformerPooling.HiddenStates.value}"
        )
        return None


class BertPoolingLayer(tf.keras.layers.Layer):
    def call(
        self,
        inputs,
        pooling_type,
        transformer_pooling_strategy=None,
        transformer_start_index=-1,
        transformer_end_index=-1,
    ):
        verify_bert_pooling_input(
            pooling_type,
            transformer_pooling_strategy,
            transformer_start_index,
            transformer_end_index,
        )

        if pooling_type == TransformerPooling.LastHiddenState:
            last_hidden_state = inputs[TransformerPooling.LastHiddenState.value]
            return tf.reduce_mean(last_hidden_state, axis=1)

        if pooling_type == TransformerPooling.Pooler:
            pooler = inputs[TransformerPooling.Pooler.value]
            return pooler

        if pooling_type == TransformerPooling.HiddenStates:
            selector = inputs[TransformerPooling.HiddenStates.value]

            number_of_layers = len(selector) - 1
            index_start_from_behinde = number_of_layers - transformer_start_index
            index_end_from_behinde = number_of_layers - transformer_end_index + 1

            selector = selector[index_start_from_behinde:index_end_from_behinde]

            if transformer_pooling_strategy in [
                TransformerPoolingStrategy.ConcatAverage,
                TransformerPoolingStrategy.ConcatCLS,
            ]:
                concatened = tf.concat(selector, axis=2)

                if transformer_pooling_strategy == TransformerPoolingStrategy.ConcatCLS:
                    cls = concatened[:, 0, :]
                    return cls
                else:
                    averaged_sentence = tf.reduce_mean(concatened, axis=1)
                    return averaged_sentence
            else:
                tf_tensor = tf.convert_to_tensor(selector)
                averaged = tf.reduce_mean(tf_tensor, axis=0)
                if transformer_pooling_strategy == TransformerPoolingStrategy.CLS:
                    cls = averaged[:, 0, :]
                    return cls
                else:
                    averaged_sentence = tf.reduce_mean(averaged, axis=1)
                    return averaged_sentence


In [76]:
from src.experiments.instances.neural_nets.transformer_with_dense_head import TransformerWithDenseHeadExperiment

In [77]:
exp = TransformerWithDenseHeadExperiment()

In [80]:
model1 = exp.get_model(False, model_name, 10, 512, None)

In [65]:
input_ids = tf.keras.layers.Input(shape=(512, ), name='input_ids', dtype='int32')
mask = tf.keras.layers.Input(shape=(512, ), name='attention_mask', dtype='int32')

embeddings = transformer(input_ids, attention_mask=mask)  # we only keep tensor 0 (last_hidden_state)
X = BertPoolingLayer()(embeddings, TransformerPooling.Pooler)
#X = tf.keras.layers.GlobalMaxPool1D()(embeddings)  # reduce tensor dimensionality
X = tf.keras.layers.BatchNormalization()(X)

X = tf.keras.layers.Dense(128, activation='relu')(X)
X = tf.keras.layers.Dropout(0.2)(X)
y = tf.keras.layers.Dense(10, activation='softmax', name='outputs')(X)  # adjust based on number of sentiment classes

model = tf.keras.Model(inputs=[input_ids, mask], outputs=y)

In [66]:
model.layers[2].trainable = False

In [81]:
model1.summary()

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 tf_bert_model_2 (TFBertModel)  TFBaseModelOutputWi  109482240   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                         

In [82]:
model1.compile(loss=settings.loss, optimizer=settings.optimizer, metrics=settings.metric)

In [53]:
train = data[0].take(1000)
val = data[0].take(1000)
test = data[0].take(1000)

In [84]:
history = model1.fit(
   prepare_dataset_from_tokenizer(train_ds, tokenizer)
    .shuffle(buffer_size=30000)
    .cache()
    .batch(32)
    .prefetch(4),
    validation_data=prepare_dataset_from_tokenizer(val_ds, tokenizer).batch(1),
    epochs=2
)

Epoch 1/2
  2/113 [..............................] - ETA: 1:59:30 - loss: 3.2204 - accuracy: 0.1094

KeyboardInterrupt: 

In [275]:
res = model.predict(prepare_dataset_from_tokenizer(test, tokenizer).take(10).batch(1))

In [276]:
res.shape

(10, 10)

In [277]:
import numpy as np

In [278]:
np.argmax(res, axis=1)

array([0, 0, 0, 8, 0, 0, 0, 0, 8, 0])

In [377]:
for x in prepare_dataset_from_tokenizer(train, tokenizer).batch(10):
    text, label = x
    output = transformer(text, output_hidden_states=True)
    output = BertPoolingLayer()(output, TransformerPooling.HiddenStates)
    #print(output)
    break

B


In [372]:
for x in prepare_dataset_from_tokenizer(dataset, tokenizer).batch(10):
    print(x)
    break

NameError: name 'dataset' is not defined

Run model experiment with to lower

... find best preprocessing

# Test ideas

- one dataset - combination of preprocessing
- size of input (k) - deps on bert - make statistics
- type of transformer - distilbert, larbe bert etc
- head of transformer - 
- encoding of transformer
- classic model of tranformer
- testování proti Glove LSTM, Embedding Dense, Glove LSTM, Glove Dense
