In [8]:
import os
import sys

def adding_module_path():
    module_path = os.path.abspath(os.path.sep.join([".."]*1))

    if module_path not in sys.path:
        sys.path.append(module_path)

adding_module_path()

from src.config.run_prep import run_prep
from src.utils.log_juypter import add_experiment_jupyter_logger

run_prep()
add_experiment_jupyter_logger(os.getcwd())

Running preperation of packages


[nltk_data] Downloading package punkt to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/usp/pro0255/diploma/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


<_io.TextIOWrapper name='/home/usp/pro0255/diploma/vizualization/jupyter_log.txt' mode='a+' encoding='UTF-8'>

In [56]:
from src.tokenizers.prepare_dataset_from_tokenizer import \
    prepare_dataset_from_tokenizer
from src.utils.create_dataset_from_dataframe import create_dataset_from_Xy
from src.tokenizers.transformer_tokenizer import TransformerTokenizer
from src.types.transformer_name import TransformerName
from src.vectorizers.transformer.distil_bert_base_vectorizer import \
    DistilBertBaseUncasedVectorizer
from transformers import AutoConfig, TFAutoModel
import tensorflow as tf

In [57]:
SENTENCE = ["To be, or not to be? That is the question ..."]
AUTHOR = [0]

MAP = {
    0: "Shakespeare"
}

train_df = create_dataset_from_Xy(SENTENCE, AUTHOR)

In [71]:
tokenizer = TransformerTokenizer(
    TransformerName.DistilBertBaseUncased.value,
    None,
    max_len=20,
)

Tokenizer with max len = 20


In [72]:
train_ds_trans = prepare_dataset_from_tokenizer(
    train_df, tokenizer
).batch(1)

In [73]:
config = AutoConfig.from_pretrained(
    TransformerName.DistilBertBaseUncased.value, output_hidden_states=True
)
transformer = TFAutoModel.from_config(config)

In [74]:
for x in train_ds_trans:
    value, target = x
    print('original --> ', SENTENCE[0])
    print()
    
    
    print(value)
    
    
    print('input_ids --> ', value['input_ids'])
    print()
    back = tokenizer.tokenizer.convert_ids_to_tokens(value['input_ids'][0])
    print('back_to_tokens --> ', back)
    print()
    
        
    print('attention_mask --> ', value['attention_mask'])
    print()
    print('target --> ', target)
    
    print()
    output = transformer(value)['hidden_states']
    print('output shape -->', tf.shape(output))
    
    print()
    print('output -->', output)

original -->  To be, or not to be? That is the question ...

{'input_ids': <tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[ 101, 2000, 2022, 1010, 2030, 2025, 2000, 2022, 1029, 2008, 2003,
        1996, 3160, 1012, 1012, 1012,  102,    0,    0,    0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]],
      dtype=int32)>}
input_ids -->  tf.Tensor(
[[ 101 2000 2022 1010 2030 2025 2000 2022 1029 2008 2003 1996 3160 1012
  1012 1012  102    0    0    0]], shape=(1, 20), dtype=int32)

back_to_tokens -->  ['[CLS]', 'to', 'be', ',', 'or', 'not', 'to', 'be', '?', 'that', 'is', 'the', 'question', '.', '.', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]']

attention_mask -->  tf.Tensor([[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]], shape=(1, 20), dtype=int32)

target -->  tf.Tensor([0], shape=(1,), dtype=int32)

output shape --> tf.Tensor([  7   1  20 768], shape=(4,), dtype=int32)

output -->